name: Bug Report
description: Report a reproducible bug with the OpenSprinkler firmware (NOT hardware, weather, or UI/app, as those have their own repos)
title: "[Bug] <brief summary here>"
labels: [bug]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Please fill out **all** sections below before submitting. Incomplete reports (especially missing version info) may be closed.

  - type: input
    id: firmware-version
    attributes:
      label: Firmware Version
      description: The firmware version running on your OpenSprinkler (e.g., 2.2.1(1)).
      placeholder: "e.g., 2.2.1(1)"
    validations:
      required: true

  - type: input
    id: hardware-version
    attributes:
      label: Hardware Version
      description: The hardware revision of your OpenSprinkler device (e.g., v3.3 AC, v3.2 DC, v3.2 Latch).
      placeholder: "e.g., v3.3 AC"
    validations:
      required: true

  - type: textarea
    id: bug-description
    attributes:
      label: Bug Description
      description: Clearly describe the issue. What did you expect to happen? What actually happened?
      placeholder: "Describe the bug here"
    validations:
      required: true

  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: Steps to Reproduce
      description: Provide a list of steps that cause the issue.
      placeholder: |
        1. Go to '...'
        2. Set '...'
        3. Click '...'
        4. See error
    validations:
      required: true

  - type: textarea
    id: error
    attributes:
      label: Errors
      description: If available, copy and paste any error messages. You can also attach screenshots.
      placeholder: "Paste error messages or screenshots here"


