blank_issues_enabled: false
contact_links:
  - name: Questions or Support
    url: https://support.opensprinkler.com
    about: Please check our support website for user manuals, support articles, FAQs, and submit support tickets there.
