site_name: OpenSprinkler Documentation
site_url: https://OpenSprinkler.github.io/OpenSprinkler-Firmware/
repo_url: https://github.com/OpenSprinkler/OpenSprinkler-Firmware

theme: readthedocs

nav:
  - 'Home': 'index.md'
  - 'FAQ': 'faq.md'
  - 'Firmware v2.2.1(4)':
    - 'User Manual': '2.2.1/221_4_manual.md'
    - 'API Reference': '2.2.1/221_4_api.md'
  - 'Troubleshooting': 'troubleshooting.md'
  - 'OpenSprinkler Pi':
    - 'Installing and Updating Firmware': 'OSPi/ospiFirmwareInstall.md'
  - 'Support Articles':
    - 'Using Weather Adjustments': 'support/weatherAdjustments.md'
    - 'How to use MQTT': 'support/mqttIntegration.md'
    - 'Setting Up Email Notifications': 'support/emailNotifications.md'
    - 'Setting Up IFTTT Notifications': 'support/iftttNotifications.md'
    - 'Using Weather Underground (WU)': 'support/weatherUnderground.md'
    - 'Interactions Between Rain Delay, Rain Sensor, and Weather Algorithm': 'support/rainWeatherInteractions.md'
    - 'Using OpenSprinkler with Amazon Echo or Google Home Assistant': 'support/homeAssistant.md'
  - 'Archived':
    - 'Previous Manuals and API docs': 'archive.md'
extra_css:
  - custom.css
markdown_extensions:
  - attr_list
  - admonition
